---

- name: check if pypy is locally downloaded
  raw: "stat {{coreos_ansible_role_path}}/files/pypy.tar.bz2"
  register: pypy_downloaded
  become: false
  ignore_errors: True
  delegate_to: 127.0.0.1
  changed_when: false

- name: download pypy locally
  get_url:
    url: "https://bitbucket.org/pypy/pypy/downloads/pypy{{ python_version }}-v{{ pypy_version }}-linux64.tar.bz2"
    dest: "{{coreos_ansible_role_path}}/files/pypy.tar.bz2"
  become: false
  delegate_to: 127.0.0.1
  when: pypy_downloaded | failed

